## Tpot creates an autmated ML pipeline

In [2]:
data_url = "https://raw.githubusercontent.com/Jcharis/Machine-Learning-Web-Apps/master/Iris-Species-Predictor-ML-Flask-App-With-Materialize.css/data/iris.csv"
data_url2 = "https://raw.githubusercontent.com/Jcharis/Python-Machine-Learning/master/Predicting_Contraceptives_MethodChoice_n_Usage_with_ML_and_TPOT/data_cmc/cmc.data"

In [4]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import MultinomialNB
!pip install MultinomialNB

ERROR: Could not find a version that satisfies the requirement MultinomialNB (from versions: none)
ERROR: No matching distribution found for MultinomialNB


In [5]:
from sklearn.naive_bayes import MultinomialNB

In [6]:
import pandas as pd
import numpy as np

In [7]:
df = pd.read_csv(data_url)

In [8]:
df.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [9]:
df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [10]:
df.dtypes

sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
species          object
dtype: object

In [11]:
df.describe()

sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [13]:
df.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

In [14]:
d = {value:index for index, value in enumerate(df['species'].unique())}

In [15]:
d

{'setosa': 0, 'versicolor': 1, 'virginica': 2}

In [16]:
df['new label'] = df['species'].map(d)

In [17]:
df.head()

sepal_length  sepal_width  petal_length  petal_width species  new label
0           5.1          3.5           1.4          0.2  setosa          0
1           4.9          3.0           1.4          0.2  setosa          0
2           4.7          3.2           1.3          0.2  setosa          0
3           4.6          3.1           1.5          0.2  setosa          0
4           5.0          3.6           1.4          0.2  setosa          0

In [18]:
df

sepal_length  sepal_width  petal_length  petal_width    species  \
0             5.1          3.5           1.4          0.2     setosa   
1             4.9          3.0           1.4          0.2     setosa   
2             4.7          3.2           1.3          0.2     setosa   
3             4.6          3.1           1.5          0.2     setosa   
4             5.0          3.6           1.4          0.2     setosa   
..            ...          ...           ...          ...        ...   
145           6.7          3.0           5.2          2.3  virginica   
146           6.3          2.5           5.0          1.9  virginica   
147           6.5          3.0           5.2          2.0  virginica   
148           6.2          3.4           5.4          2.3  virginica   
149           5.9          3.0           5.1          1.8  virginica   

     new label  
0            0  
1            0  
2            0  
3            0  
4            0  
..         ...  
145          2  
146          2  
147          2  
148          2  
149          2  

[150 rows x 6 columns]

In [21]:
xfeatures = df[['sepal_length', 'sepal_width', 'petal_length', 'petal_width']]
ylabels = df['new label']

In [19]:
from sklearn.model_selection import cross_val_score

In [22]:
cv_scores = cross_val_score(LogisticRegression(), xfeatures, ylabels, cv = 10)

C:\Users\savil\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\savil\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_

In [23]:
cv_scores

array([1.        , 0.93333333, 1.        , 1.        , 0.93333333,
       0.93333333, 0.93333333, 1.        , 1.        , 1.        ])

In [24]:
print(np.mean(cv_scores))

0.9733333333333334


In [25]:
RF_cv_scores = cross_val_score(RandomForestClassifier(), xfeatures, ylabels, cv = 10)

In [26]:
RF_cv_scores

array([1.        , 0.93333333, 1.        , 0.93333333, 0.93333333,
       0.93333333, 0.86666667, 1.        , 1.        , 1.        ])

In [27]:
print(np.mean(RF_cv_scores))

0.96


In [28]:
RF_cv_scores2 = cross_val_score(RandomForestClassifier(n_estimators=100, max_depth = 2), xfeatures, ylabels, cv = 10)

In [29]:
print(np.mean(RF_cv_scores2))

0.9533333333333334


In [30]:
RF_cv_scores2

array([0.93333333, 0.93333333, 1.        , 0.93333333, 0.93333333,
       0.93333333, 0.86666667, 1.        , 1.        , 1.        ])

### Auto ML with TPOT

In [31]:
!pip install tpot

  Using cached update_checker-0.18.0-py3-none-any.whl (7.0 kB)
Processing c:\users\savil\appdata\local\pip\cache\wheels\a8\bb\8f\6b9328d23c2dcedbfeb8498b9f650d55d463089e3b8fc0bfb2\stopit-1.1.2-py3-none-any.whl


In [42]:
import tpot

In [38]:
dir(tpot)

['TPOTClassifier',
 'TPOTRegressor',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_version',
 'base',
 'builtins',
 'config',
 'decorators',
 'driver',
 'export_utils',
 'gp_deap',
 'gp_types',
 'main',
 'metrics',
 'operator_utils',
 'tpot']

In [39]:
X_train, X_test, y_train, y_test = train_test_split(xfeatures, ylabels, test_size = 0.3, random_state = 42)

In [47]:
from tpot import TPOTClassifier # This fixed the tpotclassifier not defined error

In [48]:
tpot = TPOTClassifier(generations = 5, verbosity = 2)

In [50]:
tpot.fit(X_train, y_train) # This took 5 minutes to run, also 5 minutes of my laptop sounding like a jet


Generation 1 - Current best internal CV score: 0.980952380952381

Generation 2 - Current best internal CV score: 0.980952380952381

Generation 3 - Current best internal CV score: 0.980952380952381

Generation 4 - Current best internal CV score: 0.980952380952381

Generation 5 - Current best internal CV score: 0.980952380952381

Best pipeline: GaussianNB(MLPClassifier(input_matrix, alpha=0.001, learning_rate_init=0.001))


TPOTClassifier(generations=5, verbosity=2)

### Narrative
+ The generationsin the tpot classifier basically finds the best cv score based on the x and y training data
+ After the generation checks, tpot classifier will give me the best ML pipeline to use based on what I want for the classification
+ Quite similar to PyCarets functions but requires more lines and slower run time
+ But of course we are dealing with chosing the best ML pipeline, not the best ML model
+ GaussianNB is the best pipeline to use in this scenairo according to TPOT

In [52]:
tpot.score(X_test, y_test) # Score of 1.0, very optimal result of 100% basically

1.0

In [53]:
# Export Result
tpot.export('tpot_ml_pipeline.py') # Ok so this saves the results in greater detail if I ever need to get back to it

In [54]:
# Prediction Task
ex = np.array([6.2, 3.4, 5.4, 2.3]).reshape(1,-1)

In [55]:
tpot.predict(ex)

array([2], dtype=int64)

In [56]:
d # So it predicts the target is virginica

{'setosa': 0, 'versicolor': 1, 'virginica': 2}

## Conclusion
+ From my understanding TPOT can help pick out the best pipeline, for classification or even regression
+ Just simply initialise the classifier with a fixed set of generations and verbosity
+ Verbosity basicially tells the program How much information TPOT communicates while it's running.
+ Anything set 2 or higher will have a progress bar as well as updating the generations
+ This practical task was helpful with exploring and learning the parameters of TPOT
+ However, I still don't have a clear understanding of pipelines in general and how they work
+ I need to do more theoretical research on Datapipelines so I can understand WHY I'm coding this and the importance